version: '2'

networks:
  lbry:
    driver: bridge

services:
  lbrycrd:
    build: ./lbrycrd
    ports:
      - 19000:19000
      - 19001:19001
    networks:
      - lbry

  lbryum-server:
    build: ./lbryum-server
    ports:
      - 8000:8000
      - 50001:50001
    networks:
      - lbry
